language: generic

sudo: required

services:
  - docker

before_install:
  - docker build -t pjw6531/react-test-app -f ./frontend/Dockerfile.dev ./frontend

script:
  - docker run -e CI=true pjw6531/react-test-app npm test

after_success:
  - docker build -t pjw6531/docker-test-frontend ./frontend
  - docker build -t pjw6531/docker-test-backend ./backend
  - docker build -t pjw6531/docker-test-nginx ./nginx

  - echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_ID" --password-stdin

  - docker push pjw6531/docker-test-frontend
  - docker push pjw6531/docker-test-backend
  - docker push pjw6531/docker-test-nginx

deploy:
  provider: elasticbeanstalk
  region: "ap-northeast-2"
  app: "docker-full-stack"
  env: "DockerFullStack-env"
  bucket_name: elasticbeanstalk-ap-northeast-2-128529754877
  bucket_path: "docker-full-stack"
  on:
    branch: master
  
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_ACCESS_KEY